export default [
  {
    id: '8dc90f27-76e7-4714-90cf-5e2c4b222745',
    name: 'Fire Door',
    slug: 'fire-door',
    category: 'fire-protection-system',
    order: 1,
    specs: [{ label: 'Rating', value: '90 min' }],
    description: 'Heavy-duty fire-rated door',
  },
  {
    id: '691b1601-2656-461e-a70f-640c6444a87d',
    name: 'Smoke Detector',
    slug: 'smoke-detector',
    category: 'fire-detection-alarm-system',
    order: 2,
    specs: [],
    description: 'Addressable smoke detector',
  },
  {
    id: '03397721-76a5-4758-9149-84b54050771d',
    name: 'Dup',
    slug: 'test-update',
    category: 'fire-extinguisher',
    order: 0,
    specs: [],
  },
  {
    id: '0ef39563-6209-4b52-afea-d009fc5fa63a',
    name: 'test product 1',
    slug: 'test-product-1',
    category: 'ms-seamless-pipe',
    image: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=600&auto=format&fit=crop&q=80',
    order: 10,
    graphicType: 'ISO 7010 Certified',
    specs: [{ label: 'test', value: '4 to 6 Meters' }],
    description: 'Tsest',
  },
  {
    id: 'fa-01',
    name: 'Addressable Fire Alarm Control Panel',
    slug: 'addressable-fire-alarm-control-panel',
    category: 'fire-detection-alarm-system',
    order: 1,
    specs: [
      { label: 'Brand', value: 'Safemet' },
      { label: 'Loops', value: '1-8 Loops' },
    ],
    description: 'Intelligent addressable fire alarm control panel',
    image: 'controlPanel',
  },
  {
    id: 'fs-01',
    name: 'CO2 Flooding System',
    slug: 'co2-flooding-system',
    category: 'fire-suppression-system',
    order: 1,
    specs: [
      { label: 'Agent', value: 'CO2' },
      { label: 'Pressure', value: '30-200 bar' },
    ],
    description: 'CO2 gas fire suppression system for server rooms',
    image: 'reliefValve',
  },
  {
    id: 'fe-01',
    name: 'ABC Dry Chemical Extinguisher',
    slug: 'abc-dry-chemical',
    category: 'fire-extinguisher',
    order: 1,
    specs: [
      { label: 'Capacity', value: '5kg' },
      { label: 'Rating', value: 'ABC 9A, 113B' },
    ],
    description: 'Multi-purpose dry chemical fire extinguisher',
    image: 'extinguisher3kg',
  },
  {
    id: 'msp-01',
    name: 'MS Seamless Pipe Schedule 40',
    slug: 'ms-seamless-pipe-s40',
    category: 'ms-seamless-pipe',
    order: 1,
    specs: [
      { label: 'Standard', value: 'ASTM A106 Grade B' },
      { label: 'Schedule', value: 'SCH 40' },
    ],
    description: 'Standard weight seamless carbon steel pipe',
    image: 'butterflyValve',
  },
  {
    id: 'fp-02',
    name: 'Diesel Fire Pump',
    slug: 'diesel-fire-pump',
    category: 'fire-protection-system',
    order: 2,
    specs: [
      { label: 'Brand', value: 'Safemet' },
      { label: 'Capacity', value: '250 GPM' },
    ],
    description: 'Diesel engine driven fire pump',
    image: 'dieselPump',
  },
  {
    id: 'fe-02',
    name: 'CO2 5kg Extinguisher',
    slug: 'co2-5kg',
    category: 'fire-extinguisher',
    order: 2,
    specs: [
      { label: 'Capacity', value: '5kg' },
      { label: 'Rating', value: '55B E' },
    ],
    description: 'CO2 fire extinguisher for electrical fires',
    image: 'extinguisherCo2',
  },
  {
    id: 'fa-02',
    name: 'Conventional Fire Alarm Panel',
    slug: 'conventional-fire-alarm-panel',
    category: 'fire-detection-alarm-system',
    order: 2,
    specs: [
      { label: 'Brand', value: 'Safemet' },
      { label: 'Zones', value: '4-32 Zones' },
    ],
    description: 'Conventional addressable fire alarm panel',
    image: 'controlPanel',
  },
];